version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb11-board
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: board
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - "43306:3306"
    volumes:
      - mariadb_board_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=0
  redis:
    image: redis:7-alpine
    container_name: redis-board
    restart: always
    ports:
      - "46379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_board_data:/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-board
    restart: always
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-board:19092"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_board_data:/var/lib/kafka/data

volumes:
  mariadb_board_data:
  redis_board_data:
  kafka_board_data: